### ISSUE TITLE
implement CONS option

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#78]
Stumpless currently does not support the `STUMPLESS_OPTION_CONS` option despite providing it in its header files. This option is meant to mirror the `LOG_CONS` option from `syslog.h` in functionality, which causes messages to be written to the system console if there is a problem sending them to the target.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

First, have a look at the documentation for `stumpless_get_option`, `stumpless_set_option`, and `stumpless_unset_option` in `include/stumpless/target.h`. You will not need to modify any of these, but you will use them in your implementation so they are important to understand. Also be sure to understand how `stumpless_get_cons_stream` works, as you'll need it to retrieve the current console stream.

Next, check out `stumpless_add_entry` in `src/target.c`. This is the workhorse function for logging messages, and is a good place to put the logic to handle this option. Get the result from the calls to the sendto functions, and if the result code indicates failure (less than zero) and the option is set on the target, then print the formatted message to the console.

Don't forget to document the option after you implement it in `include/stumpless/option.h`.

Once you have implemented this, be sure to add a test for the functionality. Test code already exists to make sure that setting and unsetting the option behaves as expected - look for `TEST( SetOption, Pid )` in `test/function/target.cpp`. Use this test as a starting point to create a new test that logs a message before and after setting the option. To cause a failure, you can use a stream target with a read only stream so that attempts to write to it fail. You can see an example of this strategy in the unit test suite for stream targets - look for `TEST( StreamTargetWriteTest, ReadOnlyStream )` in `test/function/target/stream.cpp`. To capture output, set the console stream to your own custom stream using `stumpless_set_cons_stream`.

**Comment by matthew-macgregor** [comment]
Hello, @goatshriek. I'd like to work on this issue. I've already scoped out the code based on your description above (and familiarized myself with the various `LOG_*` options to `openlog`). It looks straightforward, but I'd like some direction on a few things.

#### Errors

- In the case that one of the `sendto_*` functions fails it sets an error. If `STUMPLESS_OPTION_CONS` is set, presumably I'd want to preserve the original error (if sending to the target did fail)?
- In the above case, in the unlikely scenario where write to system console also failed (?), what error should be reported? The original send to failure or something related to the console write?
- I noticed that `stumpless_get_option` calls `clear_error` internally. It would make sense to only check if `STUMPLESS_OPTION_CONS` is set _after_ the send to target has failed (efficiency), but this clears the error that was set trying to send to the target. I have a few ideas for how to approach this but wanted to get your advice first.

#### Misc

- Should `console` be a target? I was looking through the code and it seems almost identical to the file target (except I don't think we need the synchronization primitives since it's guaranteed by the std?).

Let me know if you'd like me to tackle this issue!

**Comment by goatshriek** [comment]
Hi Matthew, these are all excellent questions!

For the error code itself, I would prefer to preserve the original error as you presume, since it will probably be what the caller cares the most about.

I hadn't thought of the scenario of cascading failures, which does complicate things a bit. Again though, I would prefer to keep the original, since I imagine a file stream-based error being potentially confusing when logging to a network target without more context provided back. There's not currently a way to capture multiple errors, and that seems like a lot to do for this change. Perhaps a per-target error structure? Food for thought for a future change.

Good catch on the error being cleared by `stumpless_get_option`; any public function will clear the error when it is called (or trample it if it fails). In cases like this I usually create an `unchecked_` version of the function that omits error checks and handling, and call that from both the public version and any other place it's needed. There are a few of these in `src/entry.c` if you want to see what that looks like. Of course, feel free to follow another path if you think there is a better one.

The underlying console stream could absolutely be held in a target (I believe that's what you are asking?). The thread of "good first issue" refactoring I had in mind for this set of functionality does have it moving to that eventually, I just haven't put together a detailed issue for it yet. If you'd like to tackle that as part of this or later on, please, feel free! The issue of stomping on the original error code may make this approach less straightforward than I had originally thought though...

I will gladly reserve the issue as yours to work! Let me know if something changes, and I can always free it up.

**Comment by matthew-macgregor** [comment]
Thanks for the feedback! Based on your thoughts, here's a summary of what I have planned for this issue:

- Implement an `unchecked_` version of `stumpless_get_option` based on examples in `src/entry.c`. That'll get me past the tradeoffs related to clearing of errors.
- Errors: In all cases, I'll preserve the original error from the target as you suggested (and I agree, that feels like the best option currently).
- Confirm that existing tests guarantee that I'm preserving the original target errors, or add tests if a few cases are missing.
- Confirm that existing tests cover `stumpless_get_cons_stream` edge cases related to my changes.
- The rest of the requirements you mentioned in the original description of the issue.

Future (potential) features that I won't tackle here since they probably deserve their own issues for design/discussion:

- **Capture multiple errors per target**. I did a little investigation on this earlier and it seems like we could change the internal implementation to an error stack without modifying the public API, but it would be a bigger change to support multiple errors per target. I think it's a good feature to add and worth further design/discussion.
- **Console stream as target**. I think this would make a lot of sense for consistency and might be useful in some cases. It probably deserves its own issue and discussion to keep the current one narrowly focused on the `*_CONS` option.

**Comment by matthew-macgregor** [comment]
Hello! I've got a PR just about ready to go (implementation, tests passing, etc.), was doing some manual testing, and ran into a few challenges that I wanted to confirm my understanding.

Test environment: `ubuntu 22.04`, `gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)` testing the network TCP target with a simple python server. After 5 logs the server force closes itself.

In the default case, closing the connection triggers `SIGPIPE`, and if unhandled it terminates the process (I think we lose one log message in this case). If handled, we're into reentrant code and I would think this would be on the Stumpless integrator to handle that case. Either way, the `CONS` option is never exercised. Otherwise, the integrator can ignore `SIGPIPE` with `SIG_IGN` and we'll hit the `CONS` code (if enabled), assuming that ignoring the signal makes sense for their application.

What's your advice on this case? At the least it seems like I should document this somewhere? Or should we think differently about the approach?

I have a simple test case that I can provide, but wanted to ask for advice before going too much further, @goatshriek.

**Comment by goatshriek** [comment]
That is definitely an important case to handle, thanks for bringing it up! I think a `SIG_IGN` is a good approach to take for the immediate change, but there should be a more robust solution that tracks the error and updates the target in the long run. If you don't mind creating a new issue for that (any test case would be _hugely_ appreciated), I can start looking into that once I've finished up the Windows Event Logging revamp that I'm working on now.

You're also welcome to take a stab at it if you want of course, just don't feel any pressure to do so. I realize that reasoning about re-entrancy in a project that's new to you can be difficult, and I've only documented the POSIX safety status (including async signal safety) of public-facing functions thus far.

**Comment by matthew-macgregor** [comment]
I added an issue (https://github.com/goatshriek/stumpless/issues/231) and did a little investigation about the options, which I've documented in the description. It _might_ be a small change to deal with the signal just on the send call.

The `CONS` option works with `SIG_IGN`, so I'm going to proceed with wrapping up testing on this issue and get a PR in for it.

**Comment by goatshriek** [comment]
Awesome, thanks very much for putting in that issue, particularly with the amount of detail! I'll keep an eye out for the PR.
